### ISSUE TITLE
Fix all file paths in search.html

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ShanikaEdiriweera/temple-website#3]
Fix all file paths / to ../

**Comment by lbarros00** [comment]
where is search.html?

**Comment by lbarros00** [comment]
I will take a look

**Comment by lbarros00** [comment]
I submitted a PR for fixes I made for stylesheets and image file paths. However I could not find the other .html files that are referred in search.html. Hope this helps. #7

**Comment by ShanikaEdiriweera** [comment]
> I submitted a PR for fixes I made for stylesheets and image file paths. However I could not find the other .html files that are referred in search.html. Hope this helps. #7

Did you check whether the website is working fine after the fix?

Please do the PR to `dev` branch. I will merge it

**Comment by ShanikaEdiriweera** [comment]
@lbarros00 your PR is not complete. logo is not loading

**Comment by ShanikaEdiriweera** [comment]
close with #10
