### ISSUE TITLE
Implement Contact Page

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ShanikaEdiriweera/temple-website#5]
Add the contact.html page in pages/ and implement

**Comment by elsonlim** [comment]
Would like to try this!

Could I please get the contact details for the website?

**Comment by ShanikaEdiriweera** [comment]
> Would like to try this!
> 
> Could I please get the contact details for the website?

Thanks for taking up the challenge! Here is the maps location. It has some details. Please add dummy data to other required values. https://www.google.lk/maps/place/Chaithyalankara+Purana+Wiharaya/@6.0161335,80.2569756,14.21z/data=!4m12!1m6!3m5!1s0x0:0xf0100adecd969f13!2sChaithyalankara+Purana+Wiharaya!8m2!3d6.0101271!4d80.252144!3m4!1s0x0:0xf0100adecd969f13!8m2!3d6.0101271!4d80.252144
