### ISSUE TITLE
Implement Gallery page

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ShanikaEdiriweera/temple-website#6]
Add the gallery.html page in pages/ and implement

**Comment by singhcharanjot** [comment]
I am interested! What images do you want to include into gallery page?

**Comment by ShanikaEdiriweera** [comment]
> I am interested! What images do you want to include into gallery page?

You can find some images from here. https://www.google.lk/maps/place/Chaithyalankara+Purana+Wiharaya/@6.0161335,80.2569756,14.21z/data=!4m12!1m6!3m5!1s0x0:0xf0100adecd969f13!2sChaithyalankara+Purana+Wiharaya!8m2!3d6.0101271!4d80.252144!3m4!1s0x0:0xf0100adecd969f13!8m2!3d6.0101271!4d80.252144

If you need more add dummy images.

**Comment by ShanikaEdiriweera** [comment]
closed with #23
